server {
    listen 80;
    server_name localhost;

    # Giao diện React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Bẻ lái API xuống Backend Gateway
    location /api/ {
        # 'basecore_apigateway' là tên của service gateway trong docker-compose.yml
        # và 8080 là port nội bộ của container đó.
        proxy_pass http://basecore_apigateway:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
